name: MC-Plugin-test
version: 1.0
author: test
main: me.pluginTest.Main
description: Spawns a zombie

commands:
  summontank:
    aliases: [tank]
    description: /tank to spawn a zombie
  summonhorde:
    aliases: [horde]
    description: /horde to spawn horde
